version: '3.4'

services:
  globoticket.services.discount:
    image: ${DOCKER_REGISTRY-}globoticketservicesdiscount
    build:
      context: .
      dockerfile: GloboTicket.Services.Discount/Dockerfile
